In [16]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
x[0:3,0:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
x[:,-1]

array([3, 6, 9])