In [16]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
x[0:3,0:-1]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [18]:
x[:,-1]

array([3, 6, 9])

In [1]:
from sensor.predictor import ModelResolver
model_res = ModelResolver()
model_res.get_latest_save_model_path()

Loading environment variable from .env file


'saved_models/0/model/model.pkl'

In [3]:
model_res.get_latest_save_transformer_path()

'saved_models/0/trnasformer/transformer.pkl'

In [4]:
model_res.get_latest_save_target_encoder_path()

'saved_models/0/target_encoder/target_encoder.pkl'